##### Lehrstuhl für Analytics and Statistics (IOR)
##### Prof. Dr. Oliver Grothe
##### SoSe 2025

# Analyse multivariater Daten
## Übung 5

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import chi2
import matplotlib.pyplot as plt
data=pd.read_csv('DAXSP500.csv', sep=';',header=None)
data.head()

       0      1
0  426.1  59.91
1  422.2  60.39
2  424.4  60.13
3  422.9  59.69
4  419.5  59.50

Bilden Sie zunächst aus den absoluten Indexständen Renditedaten: Wenn Wi den Stand
eines Index am Handelstag i bezeichnet, dann bilden Sie fur alle Handelstage in dem 
Datensatz (außer dem ersten) die Rendite:
Ri = (Wi − Wi−1)/Wi−1

Die Rendite gibt also die prozentuale Veränderung des Stands vom letzten Handelstag auf den aktuellen an. Nehmen Sie nur die Handelstage in dem Datensatz, Wi−1
entspricht also immer dem Wert in der Zelle über dem Wert  Wi: Sie erhalten damit
insgesamt zwei Spalten mit Tagesrenditen.

In [2]:
data_versch=data.shift(1)
data_versch.head()

       0      1
0    NaN    NaN
1  426.1  59.91
2  422.2  60.39
3  424.4  60.13
4  422.9  59.69

In [5]:
R_i=(data-data_versch)/data_versch

Teilen Sie (im Kopf) den Datensatz in einen ersten Teil vor 1995 und einen zweiten Teil
ab 1995 (der 3. Januar 1995 entspricht der Zeile 8442 im Datensatz). Standardisieren
Sie nun alle 4 Renditedatensätze (Dax vor und ab 1995 sowie SP500 vor und ab 1995),
indem Sie sie um ihren geschätzten Erwartungswert zentrieren und durch ihre geschätzte
Standardabweichung teilen.

In [6]:
R_i_vor1995=R_i.loc[:8441,:]
R_i_nach1995=R_i.loc[8442:,:]

Berechne SD

In [9]:
std_1=np.std(R_i_vor1995.loc[1:,:])
std_2=np.std(R_i_nach1995.loc[1:,:])

Standardisiere

In [10]:
R_i_vor1995_std=(R_i_vor1995-np.mean(R_i_vor1995,axis=0))/(std_1)
R_i_nach1995_std=(R_i_nach1995-np.mean(R_i_nach1995,axis=0))/(std_2)

Schätzen Sie die Kovarianzmatrizen zwischen DAX und SP500 fur die beiden Standardisierten 2-dimensionalen Zeitreihen vor 1995 und ab 1995. Warum sind diese Kovarianzmatrizen ein Schätzer fur die Korrelationsmatrizen zwischen DAX und SP500?

In [11]:
s_1=np.cov(R_i_vor1995_std.loc[1:,:],rowvar=False)
s_2=np.cov(R_i_nach1995_std.loc[1:,:],rowvar=False)
print(s_1)
print(s_2)

[[1.00011848 0.18911306]
 [0.18911306 1.00011848]]
[[1.00028145 0.52967375]
 [0.52967375 1.00028145]]

--> Schätzer für Korrelationsmatrix von DAX und S&P500

 Testen Sie auf Gleichheit der Kovarianzmatrizen.
 S.79 im Skript

In [13]:
n_1=np.size(R_i_vor1995_std.loc[1:,:],axis=0)
n_2=np.size(R_i_nach1995_std.loc[1:,:],axis=0)
p=2
c=1 - (2*p**2+3*p-1)/(6*(p+1)) * (1/(n_1-1) + 1/(n_2-1) - 1/(n_1+n_2-2))
S = 1/(n_1+n_2-2) * ((n_1-1)*s_1+(n_2-1)*s_2)

In [14]:
X_2=c * ((n_1+n_2-2)*np.log(np.linalg.det(S)) - (n_1-1)*np.log(np.linalg.det(s_1)) - (n_2-1)*np.log(np.linalg.det(s_2)))
X_2

423.0942436240159

Wert Teststatistik

In [15]:
X_2_test=chi2.ppf(1-0.05,p*(p+1)/2) 
X_2_test

7.814727903251179

In [16]:
if X_2>X_2_test:
    print("H0 wird abgelehnt!")

H0 wird abgelehnt!